version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_ANON_KEY}
