import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
  LOCALE_ID,
  APP_INITIALIZER,
} from '@angular/core';
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';

registerLocaleData(localeEs);

import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import { AuthService } from './auth/data-access/auth.services';
import {
  LucideAngularModule,
  User,
  Mail,
  Lock,
  Eye,
  Search,
  Check,
  EyeOff,
  LogOut,
  Home,
  Plus,
  Minus,
  ShoppingCart,
  Star,
  StarOff,
  StarHalf,
  Moon,
  Menu,
  Pencil,
  Trash2,
  Save,
  X,
  ChevronLeft,
  Image,
  Upload,
  GripVertical,
  ChevronUp,
  ChevronDown,
  Sun,
  Settings,
  FileText,
  Phone,
  MoreVertical,
  Info,
  AlertTriangle,
  XCircle,
  Loader2,
  PlusCircle,
  FolderOpen,
  Layers,
  Receipt,
  Folder,
  RefreshCw,
  Calendar,
  DollarSign,
  CheckCircle,
  Printer,
  Link,
  Edit3,
  FolderX,
  SearchX,
  Filter,
  Crosshair,
  ChefHat,
  MessageSquare,
  ArrowLeft,
  MessageCircle,
  Settings2,
  ShoppingBag,
} from 'lucide-angular';

import { routes } from './app.routes';

function initializeApp(authService: AuthService) {
  return () => authService.init();
}

export const appConfig: ApplicationConfig = {
providers: [
  provideBrowserGlobalErrorListeners(),
  provideZonelessChangeDetection(),
  provideHttpClient(withFetch()),
  provideClientHydration(withEventReplay()),
  provideRouter(routes, withComponentInputBinding()),
  { provide: LOCALE_ID, useValue: 'es' },
  {
    provide: APP_INITIALIZER,
    useFactory: initializeApp,
    deps: [AuthService],
    multi: true,
  },
  importProvidersFrom(
    LucideAngularModule.pick({
        User,
        Mail,
        Lock,
        Check,
        Eye,
        Search,
        EyeOff,
        LogOut,
        Home,
        Plus,
        Minus,
        ShoppingCart,
        Star,
        StarOff,
        StarHalf,
        Moon,
        Menu,
        Pencil,
        Trash2,
        Save,
        X,
        ChevronLeft,
        Image,
        Upload,
        GripVertical,
        ChevronUp,
        ChevronDown,
        FileText,
        Phone,
        Settings,
        MoreVertical,
        Sun,
        Info,
        AlertTriangle,
        CheckCircle,
        XCircle,
        Loader2,
        PlusCircle,
        FolderOpen,
        Layers,
        Receipt,
        Folder,
        RefreshCw,
        Calendar,
        DollarSign,
        Printer,
        Link,
        Edit3,
        FolderX,
        SearchX,
        Filter,
        Crosshair,
        ChefHat,
        MessageSquare,
        ArrowLeft,
        MessageCircle,
        Settings2,
        ShoppingBag,
      }),
    ),
  ],
};
