import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import {
  LucideAngularModule,
  User,
  Mail,
  Lock,
  Eye,
  Search,
  Check,
  EyeOff,
  LogOut,
  Home,
  Plus,
  Minus,
  ShoppingCart,
  Star,
  StarOff,
  StarHalf,
  Moon,
  Menu,
  Pencil,
  Trash2,
  Save,
  X,
  ChevronLeft,
  Image,
  Upload,
  GripVertical,
  ChevronUp,
  ChevronDown,
  Sun,
  Settings,
  FileText,
  MoreVertical,
  Info,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Loader2,
  PlusCircle,
  FolderOpen,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
providers: [
  provideBrowserGlobalErrorListeners(),
  provideZonelessChangeDetection(),
  provideHttpClient(withFetch()),
  provideClientHydration(withEventReplay()),
  provideRouter(routes, withComponentInputBinding()),
  importProvidersFrom(
    LucideAngularModule.pick({
        User,
        Mail,
        Lock,
        Check,
        Eye,
        Search,
        EyeOff,
        LogOut,
        Home,
        Plus,
        Minus,
        ShoppingCart,
        Star,
        StarOff,
        StarHalf,
        Moon,
        Menu,
        Pencil,
        Trash2,
        Save,
        X,
        ChevronLeft,
        Image,
        Upload,
        GripVertical,
        ChevronUp,
        ChevronDown,
        FileText,
        Settings,
        MoreVertical,
        Sun,
        Info,
        AlertTriangle,
        CheckCircle,
        XCircle,
        Loader2,
        PlusCircle,
        FolderOpen,

        
        
        
        
      }),
    ),
  ],
};
